# version: '3.8'

services:
  # =======================
  #  Microservices
  # =======================
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "3005:3000"
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - kafka
    restart: always

  product-service:
    build: ./services/product-service
    container_name: product-service
    ports:
      - "3002:3000"
    env_file:
      - ./services/product-service/.env
    depends_on:
      - kafka
    restart: always

  order-service:
    build: ./services/order-service
    container_name: order-service
    ports:
      - "3003:3000"
    env_file:
      - ./services/order-service/.env
    depends_on:
      - kafka
    restart: always

  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    ports:
      - "3004:3000"
    env_file:
      - ./services/notification-service/.env
    depends_on:
      - kafka
    restart: always
  # ============ DATABASES ============
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: microservice_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle123
      APP_USER: appuser
      APP_USER_PASSWORD: app123
    restart: unless-stopped

  # =======================
  #  Kafka (KRaft Mode)
  # =======================
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_data:/var/lib/kafka/data
    restart: unless-stopped

  # =======================
  #  Kafka UI
  # =======================
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9000:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    restart: unless-stopped

volumes:
  kafka_data:
  postgres_data:
