name: CI/CD Microservices

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-build-test:
    name: Lint, Build & Test Services
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [api-gateway, task-service, user-service]

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Install dependencies
        working-directory: ${{ matrix.service }}
        run: npm ci

      - name: 🔍 Run Linter
        working-directory: ${{ matrix.service }}
        run: npm run lint --if-present

      - name: 🧪 Run Tests
        working-directory: ${{ matrix.service }}
        run: npm run test --if-present

      - name: 🏗️ Build project
        working-directory: ${{ matrix.service }}
        run: npm run build --if-present


#   docker-build-push:
#     name: Build & Push Docker Images
#     runs-on: ubuntu-latest
#     needs: lint-build-test

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       # ========== Build & Push NestJS Services ==========
#       - name: Build & Push Auth Service (NestJS)
#         run: |
#           docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest ./services/auth-service
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest

#       - name: Build & Push Product Service (NestJS)
#         run: |
#           docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest ./services/product-service
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest

#       - name: Build & Push Notification Service (NestJS)
#         run: |
#           docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:latest ./services/notification-service
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:latest

#       # ========== Build & Push Laravel Service ==========
#       - name: Build & Push Order Service (Laravel)
#         run: |
#           docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest ./services/order-service
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest


#   deploy:
#     name: Deploy to Server
#     runs-on: ubuntu-latest
#     needs: docker-build-push
#     if: github.ref == 'refs/heads/main'

#     steps:
#       - name: SSH to server and deploy
#         uses: appleboy/ssh-action@v0.1.10
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           script: |
#             cd /path/to/microservices
#             docker-compose pull
#             docker-compose up -d --remove-orphans
